# Generated by Django 3.2.10 on 2022-03-03 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('only_veg', models.BooleanField()),
                ('only_pizza', models.BooleanField()),
                ('only_momo', models.BooleanField()),
                ('only_sweets', models.BooleanField()),
                ('only_south_indian', models.BooleanField()),
            ],
        ),
    ]
