# Generated by Django 3.2.10 on 2022-03-03 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0002_restaurants'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurants',
            name='latitude',
            field=models.DecimalField(decimal_places=20, max_digits=25),
        ),
        migrations.AlterField(
            model_name='restaurants',
            name='longitude',
            field=models.DecimalField(decimal_places=20, max_digits=25),
        ),
    ]
