# Generated by Django 4.0.3 on 2022-03-03 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0005_alter_restaurants_website'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurants',
            name='average_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
        ),
    ]
