# Generated by Django 4.0.3 on 2022-03-03 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0006_restaurants_average_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menu',
            old_name='only_momo',
            new_name='momo',
        ),
        migrations.RenameField(
            model_name='menu',
            old_name='only_pizza',
            new_name='pizza',
        ),
        migrations.RenameField(
            model_name='menu',
            old_name='only_south_indian',
            new_name='south_indian',
        ),
        migrations.RenameField(
            model_name='menu',
            old_name='only_sweets',
            new_name='sweets',
        ),
        migrations.RenameField(
            model_name='menu',
            old_name='only_veg',
            new_name='veg',
        ),
    ]
