# Generated by Django 4.0.3 on 2022-03-04 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0007_rename_only_momo_menu_momo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurants',
            name='free_delivery',
            field=models.BooleanField(default=True),
        ),
    ]
